#!/usr/bin/env python3

from subprocess import call
import codecs
import sys

HOST = "192.168.1.151"
MAC = "8fcac734ea34"
# use path to broadlink_cli from https://github.com/mjg59/python-broadlink/tree/master/cli
BROADLINK_CLI_PATH = "/home/homeassistant/.homeassistant/broadlink/broadlink_cli"

def send_packet(packet):
  call([BROADLINK_CLI_PATH, "--type", "0x2712", "--host", HOST, "--mac", MAC, "--send", packet])


cmd = sys.argv[1] #base 64

decoded = codecs.decode(cmd.encode(), 'base64')

b64 = codecs.encode(decoded, 'hex').decode()

send_packet(b64)






