#!/usr/bin/env python3

import codecs
import sys
from subprocess import PIPE, run

HOST = "192.168.1.151"
MAC = "8fcac734ea34"
#path to broadlink_cli from https://github.com/mjg59/python-broadlink/tree/master/cli
BROADLINK_CLI_PATH = "/home/homeassistant/.homeassistant/broadlink/broadlink_cli"



cmd = [BROADLINK_CLI_PATH, "--type", "0x2712", "--host", HOST, "--mac", MAC, "--learn"]
print("Learning...")
result = run(cmd, stdout=PIPE, stderr=PIPE, universal_newlines=True).stdout.split("\n")[1]

decoded = codecs.decode(result, 'hex')

b64 = codecs.encode(decoded, 'base64').decode()

print(b64.replace('\n',''))