#!/usr/bin/env python3

import json
import importlib.util
spec = importlib.util.spec_from_file_location("utils", "/home/homeassistant/.homeassistant/scripts/utils.py")
Utils = importlib.util.module_from_spec(spec)
spec.loader.exec_module(Utils)

from datetime import datetime, timedelta
import requests, json

query = """
SELECT 
    table_name AS `Table`, 
    round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB` 
FROM information_schema.TABLES 
WHERE table_schema = "hass"
""" 
res = list(Utils.execute_hass_mysql(query))

res = list(map(lambda x: (x[0], float(x[1])), res))
d = dict(res)
json = json.dumps(d)
print(json)
